### ISSUE TITLE
botgLibrary() command without SOURCES arg causes config error

### ISSUE THREAD

**Issue by Matt-Jessee** [wawiesel/BootsOnTheGround#58]
It would be nice to use botgLibrary() with CXX header files only and no CXX sources. E.G.

botgLibrary( Moonraker
    HEADERS
        moonraker/config.h.in
        moonraker/integer_polygon_traits.h
        moonraker/polygon.h
        moonraker/utils/soft_eq.h
)

However this produces the error:

CMake Error: CMake can not determine linker language for target: Moonraker
CMake Error: Cannot determine link language for target "Moonraker".

The desired fix to this issue would be to do the following:

botgLibrary( Moonraker
    LANGUAGE CXX
    HEADERS
        moonraker/config.h.in
        moonraker/integer_polygon_traits.h
        moonraker/polygon.h
        moonraker/utils/soft_eq.h
)

Currently you get the same error with this modification.

The current work-around is to use SET_TARGET_PROPERTIES

botgLibrary( Moonraker
    HEADERS
        moonraker/config.h.in
        moonraker/integer_polygon_traits.h
        moonraker/polygon.h
        moonraker/utils/soft_eq.h
)
SET_TARGET_PROPERTIES( Moonraker PROPERTIES LINKER_LANGUAGE  CXX )

Looking at the botgLibrary() in BOTG.cmake, it looks like some simple logic could be added to call SET_TARGET_PROPERTIES() if the SOURCES arg is empty but LANGUAGE arg is set appropriately.

Also, nice to have documentation on the LANGUAGE argument in the botgLibrary() description.

**Comment by wawiesel** [comment]
Matt, in your BootsOnTheGround.in, change to point to 'develop' branch instead of 'master' to test this change to see if it works for you.

**Comment by Matt-Jessee** [comment]
I think the SET_TARGET_PROPERTIES needs to be after the call to TRIBUTES_ADD_LIBRARY. 

I think deleting your SET_TARGET_PROPERTIES on line 205 and adding the following after TRIBITS_ADD_LIBRARY will work.

        IF( NOT "${library_LANGUAGE}" STREQUAL "" )
            SET_TARGET_PROPERTIES( "${name}" PROPERTIES LINKER_LANGUAGE "${library_LANGUAGE}" )
        ENDIF()


I am having trouble making local changes to BOTG and testing them out. Maybe you can swing by and show me later today.

**Comment by wawiesel** [comment]
This appears to be fixed now.
